name: CI/CD

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        # Run the lint command
      - name: Run lint
        run: npm run lint
        # Run another command for format check
      - name: Run format check
        run: npm run format

      #   - name: Build Next.js app
      #     run: npm run build
      - name: Check commit changes
        uses: JamesIves/github-pages-deploy-action@v4
        # with:
        #   folder: build
